import { parse, parseFragment, serialize } from 'parse5';

const elements = (node) => (node.childNodes ?? []).filter((n) => !n.nodeName.startsWith('#'));

// Where a node's source text ends, as { end, tailEnd }. Implied end tags (`<li>a<li>b`) have no
// endTag, and parse5's endOffset for them can swallow the parent's closing tag, so walk to the
// last child. Text after </body> or </html> (the "tail") is merged into the last text node:
// `end` stops before those tags and `tailEnd` is where the merged text really ends.
function sourceEnd(source, node) {
  const loc = node.sourceCodeLocation;
  if (loc.endTag) return { end: loc.endTag.endOffset };
  if (node.nodeName === '#text') {
    const cut = source.slice(loc.startOffset, loc.endOffset).search(/<\/(body|html)[\s>]/i);
    return cut === -1 ? { end: loc.endOffset } : { end: loc.startOffset + cut, tailEnd: loc.endOffset };
  }
  const last = node.childNodes?.at(-1);
  if (!last) return { end: loc.startTag?.endOffset ?? loc.endOffset };
  if (!last.sourceCodeLocation) throw new Error("Can't locate this element's end in the file.");
  return sourceEnd(source, last);
}

/**
 * Replace the inner HTML of the element the user edited in the browser.
 * `before` is the element's innerHTML when editing started; it must match the source exactly
 * (after normalizing), so script-generated or since-changed content is never overwritten.
 * `path` (child-element indices from <body>) only breaks ties between identical elements.
 */
export function applyEdit(source, { tag, path, before, after }) {
  const doc = parse(source, { sourceCodeLocationInfo: true });
  const body = elements(elements(doc).find((n) => n.nodeName === 'html')).find(
    (n) => n.nodeName === 'body',
  );
  const want = serialize(parseFragment(before));
  const matches = [];
  const walk = (node, nodePath) =>
    elements(node).forEach((child, i) => {
      const childPath = [...nodePath, i];
      if (
        child.nodeName === tag &&
        child.sourceCodeLocation?.startTag &&
        serialize(child) === want
      ) {
        matches.push({ node: child, samePath: childPath.join() === path.join() });
      }
      walk(child, childPath);
    });
  walk(body, []);

  const samePath = matches.filter((m) => m.samePath);
  const hit = matches.length === 1 ? matches[0] : samePath.length === 1 ? samePath[0] : null;
  if (!hit) {
    throw new Error(
      matches.length
        ? 'Several identical elements match this edit, so it was not applied.'
        : "This element's content isn't in the file as-is (it may be generated by a script, or the file changed).",
    );
  }
  const loc = hit.node.sourceCodeLocation;
  const last = hit.node.childNodes.at(-1);
  const start = loc.startTag.endOffset;
  const { end, tailEnd = end } = loc.endTag
    ? { end: loc.endTag.startOffset }
    : last
      ? sourceEnd(source, last)
      : { end: start };
  // `after` already contains the merged tail text, so keep only the closing tags from it.
  const closing = source.slice(end, tailEnd).match(/<\/(body|html)[^>]*>/gi)?.join('') ?? '';
  return source.slice(0, start) + after + closing + source.slice(tailEnd);
}
