import { parse, parseFragment, serialize } from 'parse5';

const elements = (node) => (node.childNodes ?? []).filter((n) => !n.nodeName.startsWith('#'));

// Where a node's source text ends. Implied end tags (`<li>a<li>b`) have no endTag, and
// parse5's endOffset for them can swallow the parent's closing tag, so walk to the last child.
// Text after </body> or </html> is merged into the last text node; stop before those tags.
function sourceEnd(source, node) {
  const loc = node.sourceCodeLocation;
  if (loc.endTag) return loc.endTag.endOffset;
  if (node.nodeName === '#text') {
    const cut = source.slice(loc.startOffset, loc.endOffset).search(/<\/(body|html)[\s>]/i);
    return cut === -1 ? loc.endOffset : loc.startOffset + cut;
  }
  const last = node.childNodes?.at(-1);
  if (!last) return loc.startTag?.endOffset ?? loc.endOffset;
  if (!last.sourceCodeLocation) throw new Error("Can't locate this element's end in the file.");
  return sourceEnd(source, last);
}

/**
 * Replace the inner HTML of the element the user edited in the browser.
 * `before` is the element's innerHTML when editing started; it must match the source exactly
 * (after normalizing), so script-generated or since-changed content is never overwritten.
 * `path` (child-element indices from <body>) only breaks ties between identical elements.
 */
export function applyEdit(source, { tag, path, before, after }) {
  const doc = parse(source, { sourceCodeLocationInfo: true });
  const body = elements(elements(doc).find((n) => n.nodeName === 'html')).find(
    (n) => n.nodeName === 'body',
  );
  const want = serialize(parseFragment(before));
  const matches = [];
  const walk = (node, nodePath) =>
    elements(node).forEach((child, i) => {
      const childPath = [...nodePath, i];
      if (
        child.nodeName === tag &&
        child.sourceCodeLocation?.startTag &&
        serialize(child) === want
      ) {
        matches.push({ node: child, samePath: childPath.join() === path.join() });
      }
      walk(child, childPath);
    });
  walk(body, []);

  const samePath = matches.filter((m) => m.samePath);
  const hit = matches.length === 1 ? matches[0] : samePath.length === 1 ? samePath[0] : null;
  if (!hit) {
    throw new Error(
      matches.length
        ? 'Several identical elements match this edit, so it was not applied.'
        : "This element's content isn't in the file as-is (it may be generated by a script, or the file changed).",
    );
  }
  const loc = hit.node.sourceCodeLocation;
  const last = hit.node.childNodes.at(-1);
  const start = loc.startTag.endOffset;
  const end = loc.endTag ? loc.endTag.startOffset : last ? sourceEnd(source, last) : start;
  return source.slice(0, start) + after + source.slice(end);
}
