import { parse, parseFragment, serialize } from 'parse5';

const elements = (node) => (node.childNodes ?? []).filter((n) => !n.nodeName.startsWith('#'));

// Where a node's source text ends, as { end, tailEnd }. Implied end tags (`<li>a<li>b`) have no
// endTag, and parse5's endOffset for them can swallow the parent's closing tag, so walk to the
// last child. Text after </body> or </html> (the "tail") is merged into the last text node:
// `end` stops before those tags and `tailEnd` is where the merged text really ends.
function sourceEnd(source, node) {
  const loc = node.sourceCodeLocation;
  if (loc.endTag) return { end: loc.endTag.endOffset };
  if (node.nodeName === '#text') {
    const cut = source.slice(loc.startOffset, loc.endOffset).search(/<\/(body|html)[\s>]/i);
    return cut === -1 ? { end: loc.endOffset } : { end: loc.startOffset + cut, tailEnd: loc.endOffset };
  }
  const last = node.childNodes?.at(-1);
  if (!last) return { end: loc.startTag?.endOffset ?? loc.endOffset };
  if (!last.sourceCodeLocation) throw new Error("Can't locate this element's end in the file.");
  return sourceEnd(source, last);
}

// The parser drops one newline right after these start tags, so the source needs an extra one.
const LEADING_NEWLINE_DROPPED = new Set(['pre', 'textarea', 'listing']);

/**
 * Replace the inner HTML of the element the user edited in the browser.
 * `before` is its innerHTML when editing started; it must match the source (after normalizing),
 * so script-generated or since-changed content is never overwritten. The browser also reports
 * how many elements share this tag and content (`count`) and which one it edited (`index`); a
 * different count in the file means scripts changed the page, so the edit is refused.
 * Finally the result is re-parsed to prove that nothing but this element's content changed.
 */
export function applyEdit(source, { tag, index, count, before, after }) {
  const doc = parse(source, { sourceCodeLocationInfo: true });
  const body = elements(elements(doc).find((n) => n.nodeName === 'html')).find(
    (n) => n.nodeName === 'body',
  );
  const want = serialize(parseFragment(before));
  const matches = [];
  const walk = (node) =>
    elements(node).forEach((child) => {
      if (child.nodeName === tag && serialize(child) === want) matches.push(child);
      walk(child);
    });
  walk(body);

  const node = matches.length === count ? matches[index] : null;
  if (!node?.sourceCodeLocation?.startTag) {
    throw new Error(
      matches.length
        ? "The page's scripts add or change elements like this one, so the edit wasn't applied."
        : "This element's content isn't in the file as-is (it may be generated by a script, or the file changed).",
    );
  }
  const loc = node.sourceCodeLocation;
  const last = node.childNodes.at(-1);
  const start = loc.startTag.endOffset;
  const { end, tailEnd = end } = loc.endTag
    ? { end: loc.endTag.startOffset }
    : last
      ? sourceEnd(source, last)
      : { end: start };
  // `after` already holds the tail's merged text; keep only the tags and comments from it.
  const kept = source.slice(end, tailEnd).match(/<\/(body|html)[^>]*>|<!--[\s\S]*?-->/gi) ?? [];
  const newline =
    LEADING_NEWLINE_DROPPED.has(tag) && (after.startsWith('\n') || source[start] === '\n') ? '\n' : '';
  const next = source.slice(0, start) + newline + after + kept.join('') + source.slice(tailEnd);

  node.childNodes = parseFragment(node, after).childNodes;
  if (serialize(parse(next)) !== serialize(doc)) {
    throw new Error("The markup around this element is unusual, so the edit wasn't applied.");
  }
  return next;
}
